# Generated by Django 3.2.6 on 2023-01-21 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi Masalan (1-xona)')),
                ('owner', models.CharField(max_length=200, verbose_name='Xona egasi')),
                ('adres', models.TextField(verbose_name='Manzili')),
                ('size', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, verbose_name='Xona xaqida')),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(max_length=20, verbose_name='Nomi')),
                ('day_number', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='lat',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='long',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('adres', models.TextField(verbose_name='Manzili')),
                ('description', models.TextField(blank=True, verbose_name='Servis xaqida')),
                ('phone', models.CharField(max_length=14, verbose_name='Telefoni')),
                ('phone_2', models.CharField(blank=True, max_length=14, verbose_name="Qo'shimcha Telefoni")),
                ('working_time_from', models.TimeField(blank=True)),
                ('working_time_to', models.TimeField(blank=True)),
                ('lat', models.FloatField(blank=True, default=0.0, null=True)),
                ('long', models.FloatField(blank=True, default=0.0, null=True)),
                ('rating', models.IntegerField(default=0)),
                ('open_service', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='main.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_services', to=settings.AUTH_USER_MODEL)),
                ('working_days', models.ManyToManyField(to='main.WeekDay')),
            ],
        ),
        migrations.CreateModel(
            name='RoomPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_photos')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_photos', to='main.room')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_rooms', to='main.service'),
        ),
        migrations.CreateModel(
            name='Bron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='sana')),
                ('time_from', models.TimeField(blank=True)),
                ('time_to', models.TimeField(blank=True)),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('active', 'active'), ('cancelled', 'cancelled'), ('completed', 'completed')], default='waiting', max_length=20, verbose_name='Statusi')),
                ('canceller', models.CharField(blank=True, choices=[('owner', 'owner'), ('customer', 'customer')], max_length=20, verbose_name='Bronni bekor qiluvchi')),
                ('cancel_date', models.DateTimeField(blank=True)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_brons', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_brons', to='main.room')),
            ],
        ),
    ]
