# Generated by Django 3.2.6 on 2023-01-23 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230121_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, upload_to='service_photos'),
        ),
        migrations.CreateModel(
            name='ServicePhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_photos')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_photos', to='main.service')),
            ],
        ),
    ]
