# Generated by Django 3.2.6 on 2023-01-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230123_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='comments_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
