# Generated by Django 3.2.6 on 2023-01-24 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_service_comments_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='comments_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='servicephotos',
            name='image',
            field=models.ImageField(upload_to='service_photos'),
        ),
        migrations.AlterField(
            model_name='servicephotos',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_photos', to='main.service'),
        ),
    ]
