# Generated by Django 4.1.6 on 2023-02-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20230124_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='bron',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Kimni nomiga'),
        ),
        migrations.AddField(
            model_name='bron',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Telefon raqami'),
        ),
    ]
