# Generated by Django 4.1.6 on 2023-02-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_bron_name_bron_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bron',
            name='cancel_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bron',
            name='canceller',
            field=models.CharField(blank=True, choices=[('owner', 'owner'), ('customer', 'customer')], max_length=20, null=True, verbose_name='Bronni bekor qiluvchi'),
        ),
    ]
